version: '3.1'
services:
  adminer:
    image: adminer
    container_name: adminer
    environment:
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: database
    ports:
      - 8080:8080
  database:
    image: postgres
    restart: always
    ports:
      - ${POSTGRESQL_ADDON_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRESQL_ADDON_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_ADDON_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_ADDON_DB}
  test_database:
    image: postgres
    restart: always
    ports:
      - ${TEST_POSTGRESQL_ADDON_PORT}:5432
    environment:
      POSTGRES_USER: ${TEST_POSTGRESQL_ADDON_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRESQL_ADDON_PASSWORD}
      POSTGRES_DB: ${TEST_POSTGRESQL_ADDON_DB}
  adminer_test:
    image: adminer
    container_name: adminer_test
    environment:
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: test_database
    ports:
      - 8081:8080
  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - ${MAILDEV_WEB_PORT}:1080
      - ${MAILDEV_SMTP_PORT}:1025
